@startuml Master data synchronzation
!define AWSPuml https://raw.githubusercontent.com/awslabs/aws-icons-for-plantuml/v15.0/dist
!include AWSPuml/AWSCommon.puml
!include AWSPuml/ApplicationIntegration/APIGateway.puml
!include AWSPuml/ApplicationIntegration/MQ.puml
!include AWSPuml/ApplicationIntegration/MQBroker.puml
!include AWSPuml/Compute/LambdaLambdaFunction.puml
!include AWSPuml/General/Documents.puml
!include AWSPuml/Database/DynamoDB.puml
!include AWSPuml/General/User.puml
!include AWSPuml/Groups/AWSCloud.puml
!include AWSPuml/NetworkingContentDelivery/CloudFront.puml
!include AWSPuml/NetworkingContentDelivery/CloudFrontEdgeLocation.puml
!include AWSPuml/GroupIcons/CorporateDataCenter.puml
!include AWSPuml/General/Internetalt1.puml
!include AWSPuml/Storage/SimpleStorageService.puml

skinparam backgroundColor #EEEBDC
skinparam handwritten true

hide footbox

title Master data synchronzation
!procedure $AWSIcon($service, $line1, $line2="")
participant "$AWSImg($service)\n<b>$line1</b>\n$line2"
!endprocedure 

'participant "Booking Engine" as B
box AWS Cloud
$AWSIcon(DynamoDB, "ODS", "DB") as DB_ODS
$AWSIcon(LambdaLambdaFunction, "fnReceiver", "Lambda") as FN_SAP_RECEIVER
$AWSIcon(APIGateway, "apiMasterData", "API Gateway") as API_SAP_RECEIVER
endbox
$AWSIcon(Documents, " ", "SAP") as S

group master data synchronzation
S -> S: make master data change
S -> API_SAP_RECEIVER: masterDataChanged(event)
API_SAP_RECEIVER -> FN_SAP_RECEIVER: masterDataChanged(event)
S <- FN_SAP_RECEIVER: requestMasterData(event,Result)
FN_SAP_RECEIVER -> DB_ODS: storeMasterData(Result)

note left: store business partner and contract data to DB
end



@enduml