@startuml BookingEngine to ODS to SAP
!include includes/aws-icons.puml
!include includes/sap.puml

hide footbox

box Legacy Systems
$AWSIcon(DynamoDB, " ", "BookingEngine") as BookingEngine
endbox

box AWS Cloud
$AWSIcon(APIGateway, "ReservationReceiver", "API Gateway") as APIGateway
$AWSIcon(LambdaLambdaFunction, "ReservationReceiver", "Lambda") as ReservationReceiver
$AWSIcon(MQBroker, "Publisher", "SNS Topic") as SNS
$AWSIcon(MQ, "Subscriber", "SQS") as SQS
$AWSIcon(LambdaLambdaFunction, "ReservationProcessor", "Lambda") as ReservationProcessor
$AWSIcon(LambdaLambdaFunction, "DataCorrection", "Lambda") as DataCorrection
$AWSIcon(DynamoDB, "ODS", "Database") as Database
$AWSIcon(LambdaLambdaFunction, "Enrichment", "Lambda") as Enrichment
$AWSIcon(LambdaLambdaFunction, "Scheduler", "Lambda") as Scheduler
$AWSIcon(LambdaLambdaFunction, "SAPReceiver", "Lambda") as SAPReceiver
$AWSIcon(APIGateway, "SAP Receiver", "API Gateway") as APISAPChanges
endbox

box SAP
$AWSIcon(APIGateway, "SAP API", "Endpunkt") as SAPAPI
participant "<$sap>" as SAP
endbox

title BookingEngine to ODS to SAP

autonumber  101 "<b>[000]"
group process and store BE events
SAP -> APISAPChanges: Master Data Change Event
APISAPChanges -> SAPReceiver: Forward Event
activate SAPReceiver
SAPReceiver -> SAPAPI: Query SAP Data
SAPAPI -> SAP: Forward Event
end


autonumber  201 "<b>[000]"
group process and store BE events
BookingEngine -> APIGateway: Send Reservation\nEvent
APIGateway -> ReservationReceiver: Forward Event
activate ReservationReceiver
ReservationReceiver -> SNS: Publish Event
activate SNS
SNS --> ReservationReceiver: Confirmation
deactivate SNS
ReservationReceiver -> SQS: Send Event
activate SQS
SQS -> ReservationProcessor: Event Message
deactivate SQS
deactivate ReservationReceiver

activate ReservationProcessor
ReservationProcessor -> BookingEngine: Retrieve Booking Details
activate BookingEngine
BookingEngine --> ReservationProcessor: Booking Details
deactivate BookingEngine
ReservationProcessor -> DataCorrection: Correct\nData Errors
activate DataCorrection
DataCorrection --> ReservationProcessor: Corrected\nBooking Details
deactivate DataCorrection
ReservationProcessor -> Database: Query Master Data
activate Database
Database --> ReservationProcessor: Master Data
deactivate Database
ReservationProcessor -> Enrichment: Enrich Booking Details
activate Enrichment
Enrichment --> ReservationProcessor: Enriched Booking Details
deactivate Enrichment
ReservationProcessor -> Database: Save Booking Details
activate Database
Database --> ReservationProcessor: Confirmation
deactivate Database
deactivate ReservationProcessor
end

autonumber  301 "<b>[000]"
group monthly bulk transfer
activate Scheduler
Scheduler --> ReservationProcessor: Time-triggered Event
activate ReservationProcessor
ReservationProcessor -> SAPAPI: Send Time-triggered Data to SAP API
activate SAPAPI
SAPAPI --> ReservationProcessor: Response
deactivate SAPAPI
ReservationProcessor -> Database: Save Time-triggered Data
activate Database
Database --> ReservationProcessor: Confirmation
deactivate Database
deactivate ReservationProcessor
deactivate Scheduler
end

@enduml
